# version: '3.9'

# services:
#   attendance-service:
#     build:
#       context: ../services/attendance
#     container_name: attendance_service
#     expose:
#       - "8000"
#     networks:
#       - backend

#   # user-management-service:
#   #   build:
#   #     context: ../services/user-management
#   #   container_name: user_management_service
#   #   expose:
#   #     - "8000"
#   #   networks:
#   #     - backend

#   nginx:
#     image: nginx:alpine
#     container_name: nginx_gateway
#     ports:
#       - "80:80"
#     volumes:
#       - ./infrastructure/nginx.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - attendance-service
#       # - user-management-service
#     networks:
#       - backend

# networks:
#   backend:

version: '3.9'

services:
  # API Gateway
  api-gateway:
    build: ../api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - user-management
      - academic
      - non-academic
      - attendance
      - behavioural
      - calendar
      - dashboard
    environment:
      - PYTHONUNBUFFERED=1

  user-management:
    build: ../services/user-management
    ports:
      - "8001:8000"
    depends_on:
      - mongo

  academic:
    build: ../services/academic
    ports:
      - "8002:8000"
    depends_on:
      - mongo

  non-academic:
    build: ../services/non-academic
    ports:
      - "8003:8000"
    depends_on:
      - mongo

  attendance:
    build: ../services/attendance
    ports:
      - "8004:8000"
    depends_on:
      - mongo

  behavioural:
    build: ../services/behavioural
    ports:
      - "8005:8000"
    depends_on:
      - mongo

  calendar:
    build: ../services/calendar
    ports:
      - "8007:8000"
    depends_on:
      - mongo

  dashboard:
    build: ../services/dashboard
    ports:
      - "8006:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - ../database/mongo/data:/data/db
    restart: always

