version: '3.9'

services:
  attendance-service:
    build:
      context: ../services/attendance
    container_name: attendance_service
    expose:
      - "8000"
    networks:
      - backend

  # user-management-service:
  #   build:
  #     context: ../services/user-management
  #   container_name: user_management_service
  #   expose:
  #     - "8000"
  #   networks:
  #     - backend

  nginx:
    image: nginx:alpine
    container_name: nginx_gateway
    ports:
      - "80:80"
    volumes:
      - ./infrastructure/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - attendance-service
      # - user-management-service
    networks:
      - backend

networks:
  backend:
